"""Edit ChatTable

Revision ID: 99d8a64c5d4e
Revises: a83dbf37eda2
Create Date: 2022-06-17 21:29:25.061785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99d8a64c5d4e'
down_revision = 'a83dbf37eda2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat', 'group_id')
    op.drop_column('chat', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('type', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('chat', sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
