"""Create Entities

Revision ID: ddf4a466a2ce
Revises: 142c16ce41b0
Create Date: 2022-06-17 20:51:09.734755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddf4a466a2ce'
down_revision = '142c16ce41b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
